# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHSm_BNlyb9YK_k4PYjmqwQzGUCAohPG
"""

scores = list(map(int, input().split()))
count_fail = sum(1 for s in scores if s < 60)
print(count_fail)